// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using crudpcapi;

#nullable disable

namespace crudpcapi.Migrations
{
    [DbContext(typeof(MysqlContext))]
    [Migration("20240605144634_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("crudpcapi.Models.Photo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("CODIGO");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<byte[]>("PhotoBytes")
                        .IsRequired()
                        .HasColumnType("longblob")
                        .HasColumnName("PHOTO_BYTES");

                    b.Property<int>("SujeitoId")
                        .HasColumnType("int")
                        .HasColumnName("CODIGO_SUJEITO");

                    b.Property<long?>("SujeitoId1")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SujeitoId1");

                    b.ToTable("PHOTOS");
                });

            modelBuilder.Entity("crudpcapi.Models.Sujeito", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("CODIGO");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AlturaAproximada")
                        .HasColumnType("int")
                        .HasColumnName("ALTURA_APROXIMADA");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CIDADE");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("COMPLEMENTO");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CPF");

                    b.Property<int>("Idade")
                        .HasColumnType("int")
                        .HasColumnName("IDADE");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("NOME");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("REFERENCIA");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("RUA");

                    b.Property<string>("Vulgo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("VULGO");

                    b.HasKey("Id");

                    b.ToTable("SUJEITOS");
                });

            modelBuilder.Entity("crudpcapi.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ID_USUARIO");

                    b.Property<byte[]>("FotoPerfil")
                        .HasColumnType("longblob")
                        .HasColumnName("FOTO_PERFIL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("NOME");

                    b.Property<string>("Role")
                        .HasColumnType("longtext")
                        .HasColumnName("ROLE");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("SENHA");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("USUARIO");

                    b.HasKey("Id");

                    b.ToTable("USERS");
                });

            modelBuilder.Entity("crudpcapi.Models.Photo", b =>
                {
                    b.HasOne("crudpcapi.Models.Sujeito", null)
                        .WithMany("Photos")
                        .HasForeignKey("SujeitoId1");
                });

            modelBuilder.Entity("crudpcapi.Models.Sujeito", b =>
                {
                    b.Navigation("Photos");
                });
#pragma warning restore 612, 618
        }
    }
}
